package tokenizer

import (
	"fmt"
	"reflect"
	"testing"
)

func TestTokenizer(t *testing.T) {
	tests := []struct {
		language          string
		text              string
		expectedTokens    []string
		expectedSentences []string
		expectedLemmas    map[string][]string
	}{
		{
			language:          "eng",
			text:              "The quick brown fox jumps over the lazy dog.",
			expectedTokens:    []string{"the", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"},
			expectedSentences: []string{"The quick brown fox jumps over the lazy dog."},
			expectedLemmas: map[string][]string{
				"the":   {"the"},
				"quick": {"quick"},
				"brown": {"brown"},
				"fox":   {"fox"},
				"jumps": {"jump"},
				"over":  {"over"},
				"lazy":  {"lazy"},
				"dog":   {"dog"},
			},
		},
		{
			language:          "swe",
			text:              "Den snabba bruna räven hoppar över den lata hunden.",
			expectedTokens:    []string{"den", "snabba", "bruna", "räven", "hoppar", "över", "den", "lata", "hunden"},
			expectedSentences: []string{"Den snabba bruna räven hoppar över den lata hunden."},
			expectedLemmas: map[string][]string{
				"den":    {"den"},
				"snabba": {"snabb"},
				"bruna":  {"brun"},
				"räven":  {"räv"},
				"hoppar": {"hoppa"},
				"över":   {"över"},
				"lata":   {"lat"},
				"hunden": {"hund"},
			},
		},
		{
			language: "deu",
			text: `Der schnelle braune Fuchs springt über den faulen Hund. Die Katze sitzt auf der Mauer und schaut den Vogel an. 
			   In einem weit entfernten Königreich lebte einst eine weise Königin, die für ihre Gerechtigkeit bekannt war. 
			   Jeden Morgen ging sie durch den großen Garten ihres Palastes und sprach mit ihren treuen Untertanen. 
			   Die Sonne schien hell und die Blumen blühten in allen Farben. 
			   Eines Tages kam ein Fremder in das Königreich und bat um eine Audienz bei der Königin. 
			   Er erzählte von fernen Ländern und spannenden Abenteuern. 
			   Die Königin hörte aufmerksam zu und beschloss, dem Fremden zu helfen. 
			   Sie gab ihm eine Karte und ein wertvolles Amulett, das ihm auf seiner Reise Schutz bieten sollte. 
			   Der Fremde dankte der Königin und machte sich auf den Weg. 
			   Monate vergingen, und eines Tages kehrte der Fremde zurück, um der Königin von seinen Erlebnissen zu berichten. 
			   Er sprach von hohen Bergen, tiefen Tälern und wilden Tieren, die er auf seiner Reise gesehen hatte. 
			   Die Königin war beeindruckt und lobte den Mut des Fremden. 
			   Sie feierten gemeinsam ein großes Fest im Palast, und alle Bewohner des Königreichs waren eingeladen. 
			   Es war ein Fest voller Freude, Musik und Tanz, das bis spät in die Nacht dauerte.`,
			expectedTokens: []string{
				"der", "schnelle", "braune", "fuchs", "springt", "über", "den", "faulen", "hund",
				"die", "katze", "sitzt", "auf", "der", "mauer", "und", "schaut", "den", "vogel", "an",
				"in", "einem", "weit", "entfernten", "königreich", "lebte", "einst", "eine", "weise", "königin", "die", "für", "ihre", "gerechtigkeit", "bekannt", "war",
				"jeden", "morgen", "ging", "sie", "durch", "den", "großen", "garten", "ihres", "palastes", "und", "sprach", "mit", "ihren", "treuen", "untertanen",
				"die", "sonne", "schien", "hell", "und", "die", "blumen", "blühten", "in", "allen", "farben",
				"eines", "tages", "kam", "ein", "fremder", "in", "das", "königreich", "und", "bat", "um", "eine", "audienz", "bei", "der", "königin",
				"er", "erzählte", "von", "fernen", "ländern", "und", "spannenden", "abenteuern",
				"die", "königin", "hörte", "aufmerksam", "zu", "und", "beschloss", "dem", "fremden", "zu", "helfen",
				"sie", "gab", "ihm", "eine", "karte", "und", "ein", "wertvolles", "amulett", "das", "ihm", "auf", "seiner", "reise", "schutz", "bieten", "sollte",
				"der", "fremde", "dankte", "der", "königin", "und", "machte", "sich", "auf", "den", "weg",
				"monate", "vergingen", "und", "eines", "tages", "kehrte", "der", "fremde", "zurück", "um", "der", "königin", "von", "seinen", "erlebnissen", "zu", "berichten",
				"er", "sprach", "von", "hohen", "bergen", "tiefen", "tälern", "und", "wilden", "tieren", "die", "er", "auf", "seiner", "reise", "gesehen", "hatte",
				"die", "königin", "war", "beeindruckt", "und", "lobte", "den", "mut", "des", "fremden",
				"sie", "feierten", "gemeinsam", "ein", "großes", "fest", "im", "palast", "und", "alle", "bewohner", "des", "königreichs", "waren", "eingeladen",
				"es", "war", "ein", "fest", "voller", "freude", "musik", "und", "tanz", "das", "bis", "spät", "in", "die", "nacht", "dauerte",
			},
			expectedSentences: []string{
				"Der schnelle braune Fuchs springt über den faulen Hund.",
				"Die Katze sitzt auf der Mauer und schaut den Vogel an.",
				"In einem weit entfernten Königreich lebte einst eine weise Königin, die für ihre Gerechtigkeit bekannt war.",
				"Jeden Morgen ging sie durch den großen Garten ihres Palastes und sprach mit ihren treuen Untertanen.",
				"Die Sonne schien hell und die Blumen blühten in allen Farben.",
				"Eines Tages kam ein Fremder in das Königreich und bat um eine Audienz bei der Königin.",
				"Er erzählte von fernen Ländern und spannenden Abenteuern.",
				"Die Königin hörte aufmerksam zu und beschloss, dem Fremden zu helfen.",
				"Sie gab ihm eine Karte und ein wertvolles Amulett, das ihm auf seiner Reise Schutz bieten sollte.",
				"Der Fremde dankte der Königin und machte sich auf den Weg.",
				"Monate vergingen, und eines Tages kehrte der Fremde zurück, um der Königin von seinen Erlebnissen zu berichten.",
				"Er sprach von hohen Bergen, tiefen Tälern und wilden Tieren, die er auf seiner Reise gesehen hatte.",
				"Die Königin war beeindruckt und lobte den Mut des Fremden.",
				"Sie feierten gemeinsam ein großes Fest im Palast, und alle Bewohner des Königreichs waren eingeladen.",
				"Es war ein Fest voller Freude, Musik und Tanz, das bis spät in die Nacht dauerte.",
			},
			expectedLemmas: map[string][]string{
				"der":           {"der"},
				"den":           {"der"},
				"dem":           {"der"},
				"die":           {"der"},
				"das":           {"der"},
				"des":           {"der"},
				"schnelle":      {"schnell"},
				"braune":        {"braun"},
				"fuchs":         {"fuchs"},
				"springt":       {"springen"},
				"über":          {"über"},
				"faulen":        {"faul"},
				"hund":          {"hund"},
				"katze":         {"katze"},
				"sitzt":         {"sitzen"},
				"auf":           {"auf"},
				"mauer":         {"mauer"},
				"und":           {"und"},
				"schaut":        {"schauen"},
				"an":            {"an"},
				"in":            {"in"},
				"einem":         {"ein"},
				"weit":          {"weit"},
				"entfernten":    {"entfernt"},
				"königreich":    {"königreich"},
				"lebte":         {"leben"},
				"einst":         {"einst"},
				"eine":          {"ein"},
				"weise":         {"weise"},
				"königin":       {"königin"},
				"für":           {"für"},
				"ihre":          {"ihr"},
				"gerechtigkeit": {"gerechtigkeit"},
				"bekannt":       {"bekannt"},
				"war":           {"sein"},
				"jeden":         {"jeder"},
				"morgen":        {"morgen"},
				"ging":          {"gehen"},
				"sie":           {"sie"},
				"durch":         {"durch"},
				"großen":        {"groß"},
				"garten":        {"garten"},
				"ihres":         {"ihr"},
				"palastes":      {"palast"},
				"sprach":        {"sprechen"},
				"mit":           {"mit"},
				"ihren":         {"ihr"},
				"treuen":        {"treu"},
				"untertanen":    {"untertan"},
				"sonne":         {"sonne"},
				"schien":        {"scheinen"},
				"hell":          {"hell"},
				"blumen":        {"blume"},
				"blühten":       {"blühen"},
				"allen":         {"all"},
				"farben":        {"farbe"},
				"eines":         {"ein"},
				"tages":         {"tag"},
				"kam":           {"kommen"},
				"ein":           {"ein"},
				"fremder":       {"fremder"},
				"bat":           {"bitten"},
				"um":            {"um"},
				"audienz":       {"audienz"},
				"bei":           {"bei"},
				"er":            {"er"},
				"erzählte":      {"erzählen"},
				"von":           {"von"},
				"fernen":        {"fern"},
				"ländern":       {"land"},
				"spannenden":    {"spannend"},
				"abenteuern":    {"abenteuer"},
				"hörte":         {"hören"},
				"aufmerksam":    {"aufmerksam"},
				"zu":            {"zu"},
				"beschloss":     {"beschließen"},
				"helfen":        {"helfen"},
				"gab":           {"geben"},
				"ihm":           {"er"},
				"karte":         {"karte"},
				"wertvolles":    {"wertvoll"},
				"amulett":       {"amulett"},
				"seiner":        {"sein"},
				"reise":         {"reise"},
				"schutz":        {"schutz"},
				"bieten":        {"bieten"},
				"sollte":        {"sollen"},
				"dankte":        {"danken"},
				"machte":        {"machen"},
				"sich":          {"sich"},
				"weg":           {"weg"},
				"monate":        {"monat"},
				"vergingen":     {"vergehen"},
				"kehrte":        {"kehren"},
				"zurück":        {"zurück"},
				"seinen":        {"sein"},
				"erlebnissen":   {"erlebnis"},
				"berichten":     {"berichten"},
				"hohen":         {"hoch"},
				"bergen":        {"berg"},
				"tiefen":        {"tief"},
				"tälern":        {"tal"},
				"wilden":        {"wild"},
				"tieren":        {"tier"},
				"gesehen":       {"sehen"},
				"beeindruckt":   {"beeindrucken"},
				"lobte":         {"loben"},
				"mut":           {"mut"},
				"feierten":      {"feiern"},
				"gemeinsam":     {"gemeinsam"},
				"großes":        {"groß"},
				"fest":          {"fest"},
				"palast":        {"palast"},
				"alle":          {"alle"},
				"bewohner":      {"bewohner"},
				"waren":         {"sein"},
				"eingeladen":    {"einladen"},
				"es":            {"es"},
				"voller":        {"voll"},
				"freude":        {"freude"},
				"musik":         {"musik"},
				"tanz":          {"tanz"},
				"bis":           {"bis"},
				"spät":          {"spät"},
				"nacht":         {"nacht"},
				"dauerte":       {"dauern"},
				"vogel":         {"vogel"},
				"fremden":       {"fremd"},
				"fremde":        {"fremd"},
				"hatte":         {"haben"},
				"im":            {"in"},
				"königreichs":   {"königreich"},
			},
		},
		{
			language: "ita",
			text: `Il rapido volpe marrone salta sopra il pigro cane. Il gatto siede sul muro e guarda l'uccello.
			   In un lontano regno viveva una volta una saggia regina conosciuta per la sua giustizia.
			   Ogni mattina passeggiava nel grande giardino del suo palazzo e parlava con i suoi fedeli sudditi.
			   Il sole splendeva luminoso e i fiori fiorivano di tutti i colori.
			   Un giorno arrivò uno straniero nel regno e chiese un'udienza con la regina.
			   Raccontò di terre lontane ed avventure emozionanti.
			   La regina ascoltò attentamente e decise di aiutare lo straniero.
			   Gli diede una mappa e un prezioso amuleto che avrebbero dovuto proteggerlo nel suo viaggio.
			   Lo straniero ringraziò la regina e si mise in viaggio.
			   Passarono mesi e un giorno lo straniero tornò per raccontare alla regina le sue esperienze.
			   Parlò di alte montagne, profondi valloni e animali selvatici che aveva visto nel suo viaggio.
			   La regina rimase impressionata e lodò il coraggio dello straniero.
			   Insieme celebrarono una grande festa nel palazzo e tutti gli abitanti del regno furono invitati.
			   Fu una festa piena di gioia, musica e danze che durò fino a tarda notte.`,
			expectedTokens: []string{
				"il", "rapido", "volpe", "marrone", "salta", "sopra", "il", "pigro", "cane",
				"il", "gatto", "siede", "sul", "muro", "e", "guarda", "luccello",
				"in", "un", "lontano", "regno", "viveva", "una", "volta", "una", "saggia", "regina", "conosciuta", "per", "la", "sua", "giustizia",
				"ogni", "mattina", "passeggiava", "nel", "grande", "giardino", "del", "suo", "palazzo", "e", "parlava", "con", "i", "suoi", "fedeli", "sudditi",
				"il", "sole", "splendeva", "luminoso", "e", "i", "fiori", "fiorivano", "di", "tutti", "i", "colori",
				"un", "giorno", "arrivò", "uno", "straniero", "nel", "regno", "e", "chiese", "unudienza", "con", "la", "regina",
				"raccontò", "di", "terre", "lontane", "ed", "avventure", "emozionanti",
				"la", "regina", "ascoltò", "attentamente", "e", "decise", "di", "aiutare", "lo", "straniero",
				"gli", "diede", "una", "mappa", "e", "un", "prezioso", "amuleto", "che", "avrebbero", "dovuto", "proteggerlo", "nel", "suo", "viaggio",
				"lo", "straniero", "ringraziò", "la", "regina", "e", "si", "mise", "in", "viaggio",
				"passarono", "mesi", "e", "un", "giorno", "lo", "straniero", "tornò", "per", "raccontare", "alla", "regina", "le", "sue", "esperienze",
				"parlò", "di", "alte", "montagne", "profondi", "valloni", "e", "animali", "selvatici", "che", "aveva", "visto", "nel", "suo", "viaggio",
				"la", "regina", "rimase", "impressionata", "e", "lodò", "il", "coraggio", "dello", "straniero",
				"insieme", "celebrarono", "una", "grande", "festa", "nel", "palazzo", "e", "tutti", "gli", "abitanti", "del", "regno", "furono", "invitati",
				"fu", "una", "festa", "piena", "di", "gioia", "musica", "e", "danze", "che", "durò", "fino", "a", "tarda", "notte",
			},
			expectedSentences: []string{
				"Il rapido volpe marrone salta sopra il pigro cane.",
				"Il gatto siede sul muro e guarda l'uccello.",
				"In un lontano regno viveva una volta una saggia regina conosciuta per la sua giustizia.",
				"Ogni mattina passeggiava nel grande giardino del suo palazzo e parlava con i suoi fedeli sudditi.",
				"Il sole splendeva luminoso e i fiori fiorivano di tutti i colori.",
				"Un giorno arrivò uno straniero nel regno e chiese un'udienza con la regina.",
				"Raccontò di terre lontane ed avventure emozionanti.",
				"La regina ascoltò attentamente e decise di aiutare lo straniero.",
				"Gli diede una mappa e un prezioso amuleto che avrebbero dovuto proteggerlo nel suo viaggio.",
				"Lo straniero ringraziò la regina e si mise in viaggio.",
				"Passarono mesi e un giorno lo straniero tornò per raccontare alla regina le sue esperienze.",
				"Parlò di alte montagne, profondi valloni e animali selvatici che aveva visto nel suo viaggio.",
				"La regina rimase impressionata e lodò il coraggio dello straniero.",
				"Insieme celebrarono una grande festa nel palazzo e tutti gli abitanti del regno furono invitati.",
				"Fu una festa piena di gioia, musica e danze che durò fino a tarda notte.",
			},
			expectedLemmas: map[string][]string{
				"il":            {"il"},
				"le":            {"il"},
				"que":           {"che"},
				"a":             {"a"},
				"pasaron":       {"passare"},
				"fueron":        {"essere"},
				"horas":         {"ora"},
				"rapido":        {"rapido"},
				"volpe":         {"volpe"},
				"marrone":       {"marrone"},
				"salta":         {"saltare"},
				"sopra":         {"sopra"},
				"pigro":         {"pigro"},
				"cane":          {"cane"},
				"gatto":         {"gatto"},
				"siede":         {"sedere"},
				"sul":           {"sul"},
				"muro":          {"muro"},
				"e":             {"e"},
				"guarda":        {"guardare"},
				"luccello":      {"uccello"},
				"in":            {"in"},
				"un":            {"un"},
				"lontano":       {"lontano"},
				"regno":         {"regno"},
				"viveva":        {"vivere"},
				"una":           {"uno"},
				"volta":         {"volta"},
				"saggia":        {"saggio"},
				"regina":        {"regina"},
				"conosciuta":    {"conosciuto"},
				"per":           {"per"},
				"la":            {"il"},
				"sua":           {"suo"},
				"giustizia":     {"giustizia"},
				"ogni":          {"ogni"},
				"mattina":       {"mattina"},
				"passeggiava":   {"passeggiare"},
				"nel":           {"in"},
				"grande":        {"grande"},
				"giardino":      {"giardino"},
				"del":           {"del"},
				"suo":           {"suo"},
				"palazzo":       {"palazzo"},
				"parlava":       {"parlare"},
				"con":           {"con"},
				"i":             {"il"},
				"suoi":          {"suo"},
				"fedeli":        {"fedele"},
				"sudditi":       {"suddito"},
				"sole":          {"sole"},
				"splendeva":     {"splendere"},
				"luminoso":      {"luminoso"},
				"fiori":         {"fiore"},
				"fiorivano":     {"fiorire"},
				"di":            {"di"},
				"tutti":         {"tutto"},
				"colori":        {"colore"},
				"giorno":        {"giorno"},
				"arrivò":        {"arrivare"},
				"uno":           {"uno"},
				"straniero":     {"straniero"},
				"chiese":        {"chiedere"},
				"unudienza":     {"udienza"},
				"raccontò":      {"raccontare"},
				"terre":         {"terra"},
				"lontane":       {"lontano"},
				"ed":            {"ed"},
				"avventure":     {"avventura"},
				"emozionanti":   {"emozionante"},
				"ascoltò":       {"ascoltare"},
				"attentamente":  {"attentamente"},
				"decise":        {"decidere"},
				"aiutare":       {"aiutare"},
				"lo":            {"lui"},
				"diede":         {"dare"},
				"mappa":         {"mappa"},
				"prezioso":      {"prezioso"},
				"amuleto":       {"amuleto"},
				"che":           {"che"},
				"avrebbero":     {"avere"},
				"dovuto":        {"dovere"},
				"proteggerlo":   {"proteggere"},
				"viaggio":       {"viaggio"},
				"ringraziò":     {"ringraziare"},
				"si":            {"sé"},
				"mise":          {"mettersi"},
				"passarono":     {"passare"},
				"mesi":          {"mese"},
				"tornò":         {"tornare"},
				"raccontare":    {"raccontare"},
				"alla":          {"al"},
				"sue":           {"suo"},
				"esperienze":    {"esperienza"},
				"parlò":         {"parlare"},
				"alte":          {"alto"},
				"montagne":      {"montagna"},
				"profondi":      {"profondo"},
				"valloni":       {"vallone"},
				"animali":       {"animale"},
				"selvatici":     {"selvatico"},
				"aveva":         {"avere"},
				"visto":         {"vedere"},
				"rimase":        {"rimanere"},
				"impressionata": {"impressionare"},
				"lodò":          {"lodare"},
				"coraggio":      {"coraggio"},
				"dello":         {"dello"},
				"insieme":       {"insieme"},
				"celebrarono":   {"celebrare"},
				"festa":         {"festa"},
				"gli":           {"il"},
				"abitanti":      {"abitante"},
				"furono":        {"essere"},
				"invitati":      {"invitare"},
				"fu":            {"essere"},
				"piena":         {"pieno"},
				"gioia":         {"gioia"},
				"musica":        {"musica"},
				"danze":         {"danza"},
				"durò":          {"durare"},
				"fino":          {"fino"},
				"tarda":         {"tardo"},
				"notte":         {"notte"},
			},
		},
		{
			language: "spa",
			text: `El rápido zorro marrón salta sobre el perezoso perro. El gato está sentado en el muro mirando al pájaro.
			   En un lejano reino vivía una vez una sabia reina conocida por su justicia.
			   Cada mañana paseaba por el gran jardín de su palacio y hablaba con sus fieles súbditos.
			   El sol brillaba luminoso y las flores florecían de todos los colores.
			   Un día llegó un extranjero al reino y pidió audiencia con la reina.
			   Contó de tierras lejanas y emocionantes aventuras.
			   La reina escuchó atentamente y decidió ayudar al extranjero.
			   Le dio un mapa y un valioso amuleto que debían protegerlo en su viaje.
			   El extranjero agradeció a la reina y partió en su viaje.
			   Pasaron meses y un día el extranjero regresó para contarle a la reina sus experiencias.
			   Habló de altas montañas, profundos valles y animales salvajes que había visto en su viaje.
			   La reina quedó impresionada y elogió el coraje del extranjero.
			   Celebraron juntos una gran fiesta en el palacio y todos los habitantes del reino fueron invitados.
			   Fue una fiesta llena de alegría, música y baile que duró hasta altas horas de la noche.`,
			expectedTokens: []string{
				"el", "rápido", "zorro", "marrón", "salta", "sobre", "el", "perezoso", "perro",
				"el", "gato", "está", "sentado", "en", "el", "muro", "mirando", "al", "pájaro",
				"en", "un", "lejano", "reino", "vivía", "una", "vez", "una", "sabia", "reina", "conocida", "por", "su", "justicia",
				"cada", "mañana", "paseaba", "por", "el", "gran", "jardín", "de", "su", "palacio", "y", "hablaba", "con", "sus", "fieles", "súbditos",
				"el", "sol", "brillaba", "luminoso", "y", "las", "flores", "florecían", "de", "todos", "los", "colores",
				"un", "día", "llegó", "un", "extranjero", "al", "reino", "y", "pidió", "audiencia", "con", "la", "reina",
				"contó", "de", "tierras", "lejanas", "y", "emocionantes", "aventuras",
				"la", "reina", "escuchó", "atentamente", "y", "decidió", "ayudar", "al", "extranjero",
				"le", "dio", "un", "mapa", "y", "un", "valioso", "amuleto", "que", "debían", "protegerlo", "en", "su", "viaje",
				"el", "extranjero", "agradeció", "a", "la", "reina", "y", "partió", "en", "su", "viaje",
				"pasaron", "meses", "y", "un", "día", "el", "extranjero", "regresó", "para", "contarle", "a", "la", "reina", "sus", "experiencias",
				"habló", "de", "altas", "montañas", "profundos", "valles", "y", "animales", "salvajes", "que", "había", "visto", "en", "su", "viaje",
				"la", "reina", "quedó", "impresionada", "y", "elogió", "el", "coraje", "del", "extranjero",
				"celebraron", "juntos", "una", "gran", "fiesta", "en", "el", "palacio", "y", "todos", "los", "habitantes", "del", "reino", "fueron", "invitados",
				"fue", "una", "fiesta", "llena", "de", "alegría", "música", "y", "baile", "que", "duró", "hasta", "altas", "horas", "de", "la", "noche",
			},
			expectedSentences: []string{
				"El rápido zorro marrón salta sobre el perezoso perro.",
				"El gato está sentado en el muro mirando al pájaro.",
				"En un lejano reino vivía una vez una sabia reina conocida por su justicia.",
				"Cada mañana paseaba por el gran jardín de su palacio y hablaba con sus fieles súbditos.",
				"El sol brillaba luminoso y las flores florecían de todos los colores.",
				"Un día llegó un extranjero al reino y pidió audiencia con la reina.",
				"Contó de tierras lejanas y emocionantes aventuras.",
				"La reina escuchó atentamente y decidió ayudar al extranjero.",
				"Le dio un mapa y un valioso amuleto que debían protegerlo en su viaje.",
				"El extranjero agradeció a la reina y partió en su viaje.",
				"Pasaron meses y un día el extranjero regresó para contarle a la reina sus experiencias.",
				"Habló de altas montañas, profundos valles y animales salvajes que había visto en su viaje.",
				"La reina quedó impresionada y elogió el coraje del extranjero.",
				"Celebraron juntos una gran fiesta en el palacio y todos los habitantes del reino fueron invitados.",
				"Fue una fiesta llena de alegría, música y baile que duró hasta altas horas de la noche.",
			},
			expectedLemmas: map[string][]string{
				"el":           {"el"},
				"a":            {"a"},
				"que":          {"que"},
				"para":         {"para"},
				"fueron":       {"ser"},
				"horas":        {"hora"},
				"pasaron":      {"passare"},
				"había":        {"haber"},
				"le":           {"il"},
				"rápido":       {"rápido"},
				"zorro":        {"zorro"},
				"marrón":       {"marrón"},
				"salta":        {"saltar"},
				"sobre":        {"sobre"},
				"perezoso":     {"perezoso"},
				"perro":        {"perro"},
				"gato":         {"gato"},
				"está":         {"estar"},
				"sentado":      {"sentar"},
				"en":           {"en"},
				"muro":         {"muro"},
				"mirando":      {"mirar"},
				"al":           {"el"},
				"pájaro":       {"pájaro"},
				"un":           {"un"},
				"lejano":       {"lejano"},
				"reino":        {"reino"},
				"vivía":        {"vivir"},
				"una":          {"uno"},
				"vez":          {"vez"},
				"sabia":        {"sabio"},
				"reina":        {"reina"},
				"conocida":     {"conocido"},
				"por":          {"por"},
				"su":           {"su"},
				"justicia":     {"justicia"},
				"cada":         {"cada"},
				"mañana":       {"mañana"},
				"paseaba":      {"pasear"},
				"gran":         {"gran"},
				"jardín":       {"jardín"},
				"de":           {"de"},
				"palacio":      {"palacio"},
				"y":            {"y"},
				"hablaba":      {"hablar"},
				"con":          {"con"},
				"sus":          {"su"},
				"fieles":       {"fiel"},
				"súbditos":     {"súbdito"},
				"sol":          {"sol"},
				"brillaba":     {"brillar"},
				"luminoso":     {"luminoso"},
				"las":          {"el"},
				"flores":       {"flor"},
				"florecían":    {"florecer"},
				"todos":        {"todo"},
				"los":          {"el"},
				"colores":      {"color"},
				"día":          {"día"},
				"llegó":        {"llegar"},
				"extranjero":   {"extranjero"},
				"pidió":        {"pedir"},
				"audiencia":    {"audiencia"},
				"contó":        {"contar"},
				"tierras":      {"tierra"},
				"lejanas":      {"lejano"},
				"emocionantes": {"emocionante"},
				"aventuras":    {"aventura"},
				"la":           {"el"},
				"escuchó":      {"escuchar"},
				"atentamente":  {"atentamente"},
				"decidió":      {"decidir"},
				"ayudar":       {"ayudar"},
				"dio":          {"dar"},
				"mapa":         {"mapa"},
				"valioso":      {"valioso"},
				"amuleto":      {"amuleto"},
				"debían":       {"deber"},
				"protegerlo":   {"proteger"},
				"viaje":        {"viaje"},
				"agradeció":    {"agradecer"},
				"partió":       {"partir"},
				"meses":        {"mes"},
				"regresó":      {"regresar"},
				"contarle":     {"contar"},
				"experiencias": {"experiencia"},
				"habló":        {"hablar"},
				"altas":        {"alto"},
				"montañas":     {"montaña"},
				"profundos":    {"profundo"},
				"valles":       {"valle"},
				"animales":     {"animal"},
				"salvajes":     {"salvaje"},
				"visto":        {"ver"},
				"quedó":        {"quedar"},
				"impresionada": {"impresionar"},
				"elogió":       {"elogiar"},
				"coraje":       {"coraje"},
				"celebraron":   {"celebrar"},
				"juntos":       {"junto"},
				"fiesta":       {"fiesta"},
				"habitantes":   {"habitante"},
				"del":          {"del"},
				"invitados":    {"invitado"},
				"fue":          {"ser"},
				"llena":        {"lleno"},
				"alegría":      {"alegría"},
				"música":       {"música"},
				"baile":        {"baile"},
				"duró":         {"durar"},
				"hasta":        {"hasta"},
				"tardas":       {"tardo"},
				"noche":        {"noche"},
			},
		},
		{
			language: "fin",
			text: `Nopea ruskea kettu hyppää laiskan koiran yli. Kissa istuu muurilla ja katsoo lintua. 
				   Eräässä kaukaisessa kuningaskunnassa eli kerran viisas kuningatar, joka oli tunnettu oikeudenmukaisuudestaan. 
				   Joka aamu hän käveli palatsinsa suuressa puutarhassa ja puhui uskollistensa kanssa. 
				   Aurinko paistoi kirkkaasti ja kukat kukkivat kaikissa väreissä. 
				   Eräänä päivänä muukalainen saapui kuningaskuntaan ja pyysi audienssia kuningattarelta. 
				   Hän kertoi kaukaisista maista ja jännittävistä seikkailuista. 
				   Kuningatar kuunteli tarkkaavaisesti ja päätti auttaa muukalaista. 
				   Hän antoi hänelle kartan ja arvokkaan amuletin, joka olisi suojana hänen matkallaan. 
				   Muukalainen kiitti kuningatarta ja lähti matkaan. 
				   Kuukaudet kuluivat, ja eräänä päivänä muukalainen palasi kertomaan kokemuksistaan kuningattarelle. 
				   Hän puhui korkeista vuorista, syvistä laaksoista ja villieläimistä, joita hän oli matkallaan nähnyt. 
				   Kuningatar oli vaikuttunut ja ylisti muukalaisen rohkeutta. 
				   He juhlivat yhdessä suuret juhlat palatsissa, ja kaikki kuningaskunnan asukkaat olivat kutsuttuina. 
				   Se oli juhla täynnä iloa, musiikkia ja tanssia, joka kesti myöhään yöhön.`,
			expectedTokens: []string{
				"nopea", "ruskea", "kettu", "hyppää", "laiskan", "koiran", "yli",
				"kissa", "istuu", "muurilla", "ja", "katsoo", "lintua",
				"eräässä", "kaukaisessa", "kuningaskunnassa", "eli", "kerran", "viisas", "kuningatar", "joka", "oli", "tunnettu", "oikeudenmukaisuudestaan",
				"joka", "aamu", "hän", "käveli", "palatsinsa", "suuressa", "puutarhassa", "ja", "puhui", "uskollistensa", "kanssa",
				"aurinko", "paistoi", "kirkkaasti", "ja", "kukat", "kukkivat", "kaikissa", "väreissä",
				"eräänä", "päivänä", "muukalainen", "saapui", "kuningaskuntaan", "ja", "pyysi", "audienssia", "kuningattarelta",
				"hän", "kertoi", "kaukaisista", "maista", "ja", "jännittävistä", "seikkailuista",
				"kuningatar", "kuunteli", "tarkkaavaisesti", "ja", "päätti", "auttaa", "muukalaista",
				"hän", "antoi", "hänelle", "kartan", "ja", "arvokkaan", "amuletin", "joka", "olisi", "suojana", "hänen", "matkallaan",
				"muukalainen", "kiitti", "kuningatarta", "ja", "lähti", "matkaan",
				"kuukaudet", "kuluivat", "ja", "eräänä", "päivänä", "muukalainen", "palasi", "kertomaan", "kokemuksistaan", "kuningattarelle",
				"hän", "puhui", "korkeista", "vuorista", "syvistä", "laaksoista", "ja", "villieläimistä", "joita", "hän", "oli", "matkallaan", "nähnyt",
				"kuningatar", "oli", "vaikuttunut", "ja", "ylisti", "muukalaisen", "rohkeutta",
				"he", "juhlivat", "yhdessä", "suuret", "juhlat", "palatsissa", "ja", "kaikki", "kuningaskunnan", "asukkaat", "olivat", "kutsuttuina",
				"se", "oli", "juhla", "täynnä", "iloa", "musiikkia", "ja", "tanssia", "joka", "kesti", "myöhään", "yöhön",
			},
			expectedSentences: []string{
				"Nopea ruskea kettu hyppää laiskan koiran yli.",
				"Kissa istuu muurilla ja katsoo lintua.",
				"Eräässä kaukaisessa kuningaskunnassa eli kerran viisas kuningatar, joka oli tunnettu oikeudenmukaisuudestaan.",
				"Joka aamu hän käveli palatsinsa suuressa puutarhassa ja puhui uskollistensa kanssa.",
				"Aurinko paistoi kirkkaasti ja kukat kukkivat kaikissa väreissä.",
				"Eräänä päivänä muukalainen saapui kuningaskuntaan ja pyysi audienssia kuningattarelta.",
				"Hän kertoi kaukaisista maista ja jännittävistä seikkailuista.",
				"Kuningatar kuunteli tarkkaavaisesti ja päätti auttaa muukalaista.",
				"Hän antoi hänelle kartan ja arvokkaan amuletin, joka olisi suojana hänen matkallaan.",
				"Muukalainen kiitti kuningatarta ja lähti matkaan.",
				"Kuukaudet kuluivat, ja eräänä päivänä muukalainen palasi kertomaan kokemuksistaan kuningattarelle.",
				"Hän puhui korkeista vuorista, syvistä laaksoista ja villieläimistä, joita hän oli matkallaan nähnyt.",
				"Kuningatar oli vaikuttunut ja ylisti muukalaisen rohkeutta.",
				"He juhlivat yhdessä suuret juhlat palatsissa, ja kaikki kuningaskunnan asukkaat olivat kutsuttuina.",
				"Se oli juhla täynnä iloa, musiikkia ja tanssia, joka kesti myöhään yöhön.",
			},
			expectedLemmas: map[string][]string{
				"nopea":                   {"nopea"},
				"ruskea":                  {"ruskea"},
				"kettu":                   {"kettu"},
				"hyppää":                  {"hypätä"},
				"laiskan":                 {"laiska"},
				"koiran":                  {"koira"},
				"yli":                     {"yli"},
				"kissa":                   {"kissa"},
				"istuu":                   {"istua"},
				"hänen":                   {"hän"},
				"korkeista":               {"korkea"},
				"vuorista":                {"vuori"},
				"syvistä":                 {"syvä"},
				"muurilla":                {"muuri"},
				"ja":                      {"ja"},
				"joita":                   {"joka"},
				"katsoo":                  {"katsoa"},
				"lintua":                  {"lintu"},
				"eräässä":                 {"eräs"},
				"kaukaisessa":             {"kaukainen"},
				"kuningaskunnassa":        {"kuningaskunta"},
				"kuningaskuntaan":         {"kuningaskunta"},
				"eli":                     {"elää"},
				"kerran":                  {"kerta"},
				"viisas":                  {"viisas"},
				"kuningatar":              {"kuningatar"},
				"kuningattarelle":         {"kuningatar"},
				"joka":                    {"joka"},
				"oli":                     {"olla"},
				"tunnettu":                {"tunnettu"},
				"oikeudenmukaisuudestaan": {"oikeudenmukaisuus"},
				"aamu":                    {"aamu"},
				"hän":                     {"hän"},
				"käveli":                  {"kävellä"},
				"palatsinsa":              {"palatsi"},
				"suuressa":                {"suuri"},
				"puutarhassa":             {"puutarha"},
				"puhui":                   {"puhua"},
				"uskollistensa":           {"uskollinen"},
				"kanssa":                  {"kanssa"},
				"aurinko":                 {"aurinko"},
				"paistoi":                 {"paistaa"},
				"kirkkaasti":              {"kirkas"},
				"kukat":                   {"kukka"},
				"kukkivat":                {"kukkia"},
				"kaikissa":                {"kaikki"},
				"väreissä":                {"väri"},
				"eräänä":                  {"eräs"},
				"päivänä":                 {"päivä"},
				"muukalainen":             {"muukalainen"},
				"muukalaista":             {"muukalainen"},
				"muukalaisen":             {"muukalainen"},
				"villieläimistä":          {"villieläin"},
				"saapui":                  {"saapua"},
				"pyysi":                   {"pyytää"},
				"audienssia":              {"audienssi"},
				"kuningattarelta":         {"kuningatar"},
				"kertoi":                  {"kertoa"},
				"kaukaisista":             {"kaukainen"},
				"maista":                  {"maa"},
				"jännittävistä":           {"jännittävä"},
				"seikkailuista":           {"seikkailu"},
				"kuunteli":                {"kuunnella"},
				"tarkkaavaisesti":         {"tarkkaavainen"},
				"päätti":                  {"päättää"},
				"auttaa":                  {"auttaa"},
				"antoi":                   {"antaa"},
				"hänelle":                 {"hän"},
				"kartan":                  {"kartta"},
				"arvokkaan":               {"arvokas"},
				"amuletin":                {"amuletti"},
				"olisi":                   {"olla"},
				"suojana":                 {"suojana"},
				"matkallaan":              {"matka"},
				"matkaan":                 {"matka"},
				"kiitti":                  {"kiittää"},
				"kuningatarta":            {"kuningatar"},
				"lähti":                   {"lähteä"},
				"kuukaudet":               {"kuukausi"},
				"kuluivat":                {"kulua"},
				"palasi":                  {"palata"},
				"kertomaan":               {"kertoa"},
				"kokemuksistaan":          {"kokemus"},
				"nähnyt":                  {"nähdä"},
				"vaikuttunut":             {"vaikuttunut"},
				"ylisti":                  {"ylistää"},
				"rohkeutta":               {"rohkeus"},
				"he":                      {"hän"},
				"juhlivat":                {"juhlia"},
				"yhdessä":                 {"yhdessä"},
				"suuret":                  {"suuri"},
				"juhlat":                  {"juhla"},
				"palatsissa":              {"palatsi"},
				"kaikki":                  {"kaikki"},
				"kuningaskunnan":          {"kuningaskunta"},
				"asukkaat":                {"asukas"},
				"olivat":                  {"olla"},
				"kutsuttuina":             {"kutsua"},
				"se":                      {"se"},
				"juhla":                   {"juhla"},
				"täynnä":                  {"täysi"},
				"iloa":                    {"ilo"},
				"musiikkia":               {"musiikki"},
				"tanssia":                 {"tanssi"},
				"kesti":                   {"kestää"},
				"myöhään":                 {"myöhä"},
				"yöhön":                   {"yö"},
				"laaksoista":              {"laakso"},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.language, func(t *testing.T) {
			tokenizer, err := New(tt.language)
			if err != nil {
				t.Fatalf("Failed to create tokenizer: %v", err)
			}

			tokens := tokenizer.GetTokens(tt.text)
			if !reflect.DeepEqual(tokens, tt.expectedTokens) {
				if len(tokens) != len(tt.expectedTokens) {
					fmt.Printf("Wrong number of tokens: want %d, got %d\n", len(tt.expectedTokens), len(tokens))
				}
				for i := range tokens {
					if tokens[i] != tt.expectedTokens[i] {
						fmt.Printf("Wrong token: want %s, got %s\n", tt.expectedTokens[i], tokens[i])
					}
				}
				t.Errorf("GetTokens() = %v, want %v", tokens, tt.expectedTokens)
			}

			sentences := tokenizer.GetSentences(tt.text)
			if !reflect.DeepEqual(sentences, tt.expectedSentences) {
				if len(sentences) != len(tt.expectedSentences) {
					t.Errorf("Got wrong number of sentences: got %d, want %d", len(sentences), len(tt.expectedSentences))
				}
				for i := range sentences {
					if sentences[i] != tt.expectedSentences[i] {
						t.Errorf("Got wrong sentence: got:\n%s\n\nwant:\n%s", sentences[i], tt.expectedSentences[i])
					}
				}
			}

			lemmas, err := tokenizer.Lemmatize(tokens)
			if err != nil {
				t.Fatalf("Lemmatize() failed: %v", err)
			}

			var wrongCount int
			for i, token := range tokens {
				expectedLemma := tt.expectedLemmas[token]
				gotLemma := lemmas[i]
				if !sliceContains(expectedLemma, gotLemma) {
					if len(expectedLemma) == 0 {
						fmt.Printf("missing expected lemma for: %s in language: %s\n", token, tt.language)
					}
					fmt.Printf("lang: %s\nwrong lemma for \"%s\": want %s, got \"%s\"\n", tt.language, token, expectedLemma, gotLemma)
					wrongCount++
				}
			}

			// Lemmatize() test fails if lemmatization accuracy is below 90%
			accuracy := 1 - float64(wrongCount)/float64(len(tokens))
			if accuracy <= 0.9 {
				t.Errorf("Lemmatize() too low accuracy for %s.\nAccuracy: %f", tt.language, accuracy)
			}
		})
	}
}

func sliceContains(slice []string, s string) bool {
	for _, v := range slice {
		if v == s {
			return true
		}
	}
	return false
}
